### ISSUE TITLE
Help? Failed add txt record. What's wrong?

### ISSUE THREAD

**Issue by yukeiyang** [alambrec/validation-hooks-certbot-godaddy#5]
Failed authorization procedure. fashionworldhongkong.com (dns-01): urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up TXT for _acme-challenge.fashionworldhongkong.com

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: fashionworldhongkong.com
   Type:   None
   Detail: DNS problem: NXDOMAIN looking up TXT for
   _acme-challenge.fashionworldhongkong.com

**I Checked Godaddy DNS, The txt record value is "none".
What's wrong?**

**Comment by alambrec** [comment]
Hi,
Are you try to run `authenticator_godaddy.sh` in `debug_mode` ?
You must uncomment the

**Comment by alambrec** [comment]
Hi,
Are you try to run `authenticator_godaddy.sh` in `debug_mode` ?
The `debug process` is described in `README.md`.
After this test, can you post your logs here ?
For your domain, it must be located in `/tmp/authenticator.fashionworldhongkong.com.log`

Keep me informed  ;)

**Comment by yukeiyang** [comment]
Hey, I Solved this issue.
