### ISSUE TITLE
authenticator doesn't work well with SAN certificates

### ISSUE THREAD

**Issue by charly4711** [alambrec/validation-hooks-certbot-godaddy#6]
The authenticator script only works well, when there's one challenge per certificate to process.
If there are multiple challenges, the script is executed multiple times and each time replaces the TXT record created by the previous iteration. Thus, by the time certbot does the validation, there is always at least one TXT record missing.

With a little tinkering, one can work around it and only do a replace when there was an entry "none" before.
(me having replaced host by dig and figuring out an authoritative name server for the domain may or may not be relevant.)

[authenticator_godaddy.sh.diff.txt](https://github.com/alambrec/validation-hooks-certbot-godaddy/files/2823879/authenticator_godaddy.sh.diff.txt)

**Comment by alambrec** [comment]
Hi @charly4711,

Thanks for your contribution 👍 

I have just created a new branch with your fix applied, named `fix_multiple_challenges_per_certificate` 
Can you clone my repository, and test it on your environment to confirm me that it's all ok ?
I ask you because I don't have any GoDaddy domain by now to test it ...

Similarly, you think it should be necessary to update `cleanup_godaddy.sh` with your new contribution on `authenticator_godaddy.sh` ?

**Comment by charly4711** [comment]
Sure, will test ... though I prolly won't get around to doing that today, or maybe tomorrow either.
Update to cleanup_godaddy.sh would have been the preferred way of dealing with the repeated calls to the authenticator. I'd have loved to just let the authenticator add (and _not_ replace TXT records), and then have the cleanup script remove the complete TXT record (and not just updated the data to "none").
However, given how the godaddy API somehow doesn't seem to support just removing a record without replacing it, I couldn't get that to work. Hence I don't see a need to modify the cleanup script.

**Comment by alambrec** [comment]
Ok. Yes, it is precisely why I replace (and _not_ add TXT records) into authenticator ... 
I also find that `remove record` function must be implemented into GoDaddy API.
I wait your confirmation to close this issue and merge `fix_multiple_challenges_per_certificate` into `master` branch.
Thanks you again for your contribution 👍

**Comment by charly4711** [comment]
Looks good to me.
The whole dns-01 challenge thing seems a little flaky due to DNS entry propagation delays and stuff, especially if you do it multiple times in a short while. But generally speaking it seems to work.

**Comment by alambrec** [comment]
Ok. I push a new commit to set in variable these parameters to ensure that everyone can set their proper values depending on their environment.
Thanks for your help 👍
